package com.marketplace.notification.entity;

public enum NotificationType {
    KYC_SUBMITTED,
    KYC_APPROVED,
    KYC_REJECTED,
    MATCH_FOUND,
    OFFER_SENT,
    OFFER_ACCEPTED,
    OFFER_REJECTED,
    OFFER_CANCELLED,
    BOOKING_CREATED,
    PAYMENT_HELD,
    DELIVERY_CODE_GENERATED,
    DELIVERY_VERIFIED,
    PAYMENT_RELEASED,
    PAYMENT_REFUNDED,
    DISPUTE_CREATED,
    DISPUTE_UNDER_REVIEW,
    DISPUTE_RESOLVED,
    DISPUTE_REJECTED,
    REVIEW_RECEIVED,
    SYSTEM_ALERT
}