spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: marketplace
    password: marketplace

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

app:
  kafka:
    enabled: true
  cors:
    allowed-origins: http://localhost:5173,http://localhost:5174,http://localhost:3000

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    com.marketplace: DEBUG
    org.springframework.security: INFO
    org.springframework.kafka: INFO
